### ISSUE TITLE
Python: OpenImageIO.AppendSubimages moved?

### ISSUE THREAD

**Issue by filmkorn** [OpenImageIO/oiio#2673]
**Describe the bug**
We merge images as multipart subimages into one. Migrating this code to oiio-2 we're running into an AttributeError and I can't find if or where this attribute was moved.

**To Reproduce**

Simplified example:

```python
>>> spec = oiio.ImageSpec()
>>> output_image = ImageOutput.create("some_target_path.exr")
>>> output_image.open("some_input.exr", spec, oiio.AppendSubimage)
AttributeError: 'module' object has no attribute 'AppendSubimage'
```

**Expected behavior**
No AttributeError is raised. The code above used to work in oiio-1.8.17.6.

**Evidence**
- See above.

**Platform information:**
 - OIIO branch/version: 2.2 beta1
 - OS: Cent7
 - C++ compiler: gcc 6.4.0
 - Any non-default build flags when you build OIIO:

Unfortunately I don't have another OIIO version at hand to check when this attribute was (re)moved. I also can't find the [OpenMode enum](https://openimageio.readthedocs.io/en/release-2.2.4.0-beta1/imageoutput.html?highlight=OpenMode#_CPPv4N4OIIO11ImageOutput8OpenModeE) in the `ImageOutput` class.

**Comment by lgritz** [comment]
OIIO 2.0 switched from using boost python to pybind11, and because that introduced some non-back-compatible changes, we took advantage of the opportunity to clean up a few other things that could only be done at a time that we were breaking compatibility.

One of those things was elimination of a number of single-use enums.  The open() method has changed so that the third "mode" argument is a string now. So just write

    output_image.open("some_input.exr", spec, "AppendSubimage")

Other choices for the mode include "Create" (the default), and "AppendMIPLevel".

**Comment by filmkorn** [comment]
Wonderful, thank you!
