### ISSUE TITLE
Fails to build with Clang 7.0

### ISSUE THREAD

**Issue by jbeich** [OpenImageIO/oiio#1994]
CC @sambler @DimitryAndric

### Problem

**Expected behavior:**  Build succeeds.

**Actual behavior:**  

```
$ c++ -v
FreeBSD clang version 7.0.0 (branches/release_70 338892) (based on LLVM 7.0.0svn)
Target: x86_64-unknown-freebsd12.0
Thread model: posix
InstalledDir: /usr/bin
```

```c++
FAILED: src/libutil/CMakeFiles/simd_test.dir/simd_test.cpp.o
/usr/bin/c++  -DUSE_FREETYPE -DUSE_OCIO=1 -DUSE_STD_REGEX -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -Iinclude -Isrc/include -I/usr/local/include/OpenEXR -isystem /usr/local/include -O3 -DNDEBUG   -Wall -Werror -fno-math-errno -Wno-unused-function -Wno-overloaded-virtual -Wno-unneeded-internal-declaration -Wno-unused-private-field -Wno-tautological-compare -Qunused-arguments -Wunknown-warning-option -Wno-unused-local-typedefs -Wno-expansion-to-defined -std=c++11 -Wno-deprecated-register -UUSE_FIELD3D -MD -MT src/libutil/CMakeFiles/simd_test.dir/simd_test.cpp.o -MF src/libutil/CMakeFiles/simd_test.dir/simd_test.cpp.o.d -o src/libutil/CMakeFiles/simd_test.dir/simd_test.cpp.o -c src/libutil/simd_test.cpp
In file included from src/libutil/simd_test.cpp:37:
src/include/OpenImageIO/simd.h:3229:29: error: argument value 340 is outside the valid range [0, 255] [-Wargument-outside-range]
    return _mm_castsi128_ps(_mm_shuffle_epi32(_mm_castps_si128(a), _MM_SHUFFLE(i3, i2, i1, i0)));
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/clang/7.0.0/include/emmintrin.h:4347:12: note: expanded from macro '_mm_shuffle_epi32'
  (__m128i)__builtin_ia32_pshufd((__v4si)(__m128i)(a), (int)(imm))
           ^                                           ~~~~~~~~~~
src/include/OpenImageIO/simd.h:6843:26: note: in instantiation of function template specialization 'OpenImageIO_v1_9::simd::shuffle_sse<4, 4, 4, 4>' requested here
    return _mm_cvtss_f32(shuffle_sse<i,i,i,i>(a.simd()));
                         ^
src/libutil/simd_test.cpp:627:27: note: in instantiation of function template specialization 'OpenImageIO_v1_9::simd::extract<4>' requested here
        OIIO_CHECK_EQUAL (extract<4>(b), 4);
                          ^
src/libutil/simd_test.cpp:1702:5: note: in instantiation of function template specialization 'test_component_access<OpenImageIO_v1_9::simd::vfloat4>' requested here
    test_component_access<vfloat4> ();
    ^
In file included from src/libutil/simd_test.cpp:37:
src/include/OpenImageIO/simd.h:3229:29: error: argument value 341 is outside the valid range [0, 255] [-Wargument-outside-range]
    return _mm_castsi128_ps(_mm_shuffle_epi32(_mm_castps_si128(a), _MM_SHUFFLE(i3, i2, i1, i0)));
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/clang/7.0.0/include/emmintrin.h:4347:12: note: expanded from macro '_mm_shuffle_epi32'
  (__m128i)__builtin_ia32_pshufd((__v4si)(__m128i)(a), (int)(imm))
           ^                                           ~~~~~~~~~~
src/include/OpenImageIO/simd.h:6843:26: note: in instantiation of function template specialization 'OpenImageIO_v1_9::simd::shuffle_sse<5, 5, 5, 5>' requested here
    return _mm_cvtss_f32(shuffle_sse<i,i,i,i>(a.simd()));
                         ^
src/libutil/simd_test.cpp:628:27: note: in instantiation of function template specialization 'OpenImageIO_v1_9::simd::extract<5>' requested here
        OIIO_CHECK_EQUAL (extract<5>(b), 5);
                          ^
src/libutil/simd_test.cpp:1702:5: note: in instantiation of function template specialization 'test_component_access<OpenImageIO_v1_9::simd::vfloat4>' requested here
    test_component_access<vfloat4> ();
    ^
In file included from src/libutil/simd_test.cpp:37:
src/include/OpenImageIO/simd.h:3229:29: error: argument value 510 is outside the valid range [0, 255] [-Wargument-outside-range]
    return _mm_castsi128_ps(_mm_shuffle_epi32(_mm_castps_si128(a), _MM_SHUFFLE(i3, i2, i1, i0)));
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/clang/7.0.0/include/emmintrin.h:4347:12: note: expanded from macro '_mm_shuffle_epi32'
  (__m128i)__builtin_ia32_pshufd((__v4si)(__m128i)(a), (int)(imm))
           ^                                           ~~~~~~~~~~
src/include/OpenImageIO/simd.h:6843:26: note: in instantiation of function template specialization 'OpenImageIO_v1_9::simd::shuffle_sse<6, 6, 6, 6>' requested here
    return _mm_cvtss_f32(shuffle_sse<i,i,i,i>(a.simd()));
                         ^
src/libutil/simd_test.cpp:629:27: note: in instantiation of function template specialization 'OpenImageIO_v1_9::simd::extract<6>' requested here
        OIIO_CHECK_EQUAL (extract<6>(b), 6);
                          ^
src/libutil/simd_test.cpp:1702:5: note: in instantiation of function template specialization 'test_component_access<OpenImageIO_v1_9::simd::vfloat4>' requested here
    test_component_access<vfloat4> ();
    ^
In file included from src/libutil/simd_test.cpp:37:
src/include/OpenImageIO/simd.h:3229:29: error: argument value 511 is outside the valid range [0, 255] [-Wargument-outside-range]
    return _mm_castsi128_ps(_mm_shuffle_epi32(_mm_castps_si128(a), _MM_SHUFFLE(i3, i2, i1, i0)));
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/clang/7.0.0/include/emmintrin.h:4347:12: note: expanded from macro '_mm_shuffle_epi32'
  (__m128i)__builtin_ia32_pshufd((__v4si)(__m128i)(a), (int)(imm))
           ^                                           ~~~~~~~~~~
src/include/OpenImageIO/simd.h:6843:26: note: in instantiation of function template specialization 'OpenImageIO_v1_9::simd::shuffle_sse<7, 7, 7, 7>' requested here
    return _mm_cvtss_f32(shuffle_sse<i,i,i,i>(a.simd()));
                         ^
src/libutil/simd_test.cpp:630:27: note: in instantiation of function template specialization 'OpenImageIO_v1_9::simd::extract<7>' requested here
        OIIO_CHECK_EQUAL (extract<7>(b), 7);
                          ^
src/libutil/simd_test.cpp:1702:5: note: in instantiation of function template specialization 'test_component_access<OpenImageIO_v1_9::simd::vfloat4>' requested here
    test_component_access<vfloat4> ();
    ^
In file included from src/libutil/simd_test.cpp:37:
src/include/OpenImageIO/simd.h:3229:29: error: argument value 680 is outside the valid range [0, 255] [-Wargument-outside-range]
    return _mm_castsi128_ps(_mm_shuffle_epi32(_mm_castps_si128(a), _MM_SHUFFLE(i3, i2, i1, i0)));
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/clang/7.0.0/include/emmintrin.h:4347:12: note: expanded from macro '_mm_shuffle_epi32'
  (__m128i)__builtin_ia32_pshufd((__v4si)(__m128i)(a), (int)(imm))
           ^                                           ~~~~~~~~~~
src/include/OpenImageIO/simd.h:6843:26: note: in instantiation of function template specialization 'OpenImageIO_v1_9::simd::shuffle_sse<8, 8, 8, 8>' requested here
    return _mm_cvtss_f32(shuffle_sse<i,i,i,i>(a.simd()));
                         ^
src/libutil/simd_test.cpp:633:27: note: in instantiation of function template specialization 'OpenImageIO_v1_9::simd::extract<8>' requested here
        OIIO_CHECK_EQUAL (extract<8>(b), 8);
                          ^
src/libutil/simd_test.cpp:1702:5: note: in instantiation of function template specialization 'test_component_access<OpenImageIO_v1_9::simd::vfloat4>' requested here
    test_component_access<vfloat4> ();
    ^
In file included from src/libutil/simd_test.cpp:37:
src/include/OpenImageIO/simd.h:3229:29: error: argument value 765 is outside the valid range [0, 255] [-Wargument-outside-range]
    return _mm_castsi128_ps(_mm_shuffle_epi32(_mm_castps_si128(a), _MM_SHUFFLE(i3, i2, i1, i0)));
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/clang/7.0.0/include/emmintrin.h:4347:12: note: expanded from macro '_mm_shuffle_epi32'
  (__m128i)__builtin_ia32_pshufd((__v4si)(__m128i)(a), (int)(imm))
           ^                                           ~~~~~~~~~~
src/include/OpenImageIO/simd.h:6843:26: note: in instantiation of function template specialization 'OpenImageIO_v1_9::simd::shuffle_sse<9, 9, 9, 9>' requested here
    return _mm_cvtss_f32(shuffle_sse<i,i,i,i>(a.simd()));
                         ^
src/libutil/simd_test.cpp:634:27: note: in instantiation of function template specialization 'OpenImageIO_v1_9::simd::extract<9>' requested here
        OIIO_CHECK_EQUAL (extract<9>(b), 9);
                          ^
src/libutil/simd_test.cpp:1702:5: note: in instantiation of function template specialization 'test_component_access<OpenImageIO_v1_9::simd::vfloat4>' requested here
    test_component_access<vfloat4> ();
    ^
In file included from src/libutil/simd_test.cpp:37:
src/include/OpenImageIO/simd.h:3229:29: error: argument value 682 is outside the valid range [0, 255] [-Wargument-outside-range]
    return _mm_castsi128_ps(_mm_shuffle_epi32(_mm_castps_si128(a), _MM_SHUFFLE(i3, i2, i1, i0)));
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/clang/7.0.0/include/emmintrin.h:4347:12: note: expanded from macro '_mm_shuffle_epi32'
  (__m128i)__builtin_ia32_pshufd((__v4si)(__m128i)(a), (int)(imm))
           ^                                           ~~~~~~~~~~
src/include/OpenImageIO/simd.h:6843:26: note: in instantiation of function template specialization 'OpenImageIO_v1_9::simd::shuffle_sse<10, 10, 10, 10>' requested here
    return _mm_cvtss_f32(shuffle_sse<i,i,i,i>(a.simd()));
                         ^
src/libutil/simd_test.cpp:635:27: note: in instantiation of function template specialization 'OpenImageIO_v1_9::simd::extract<10>' requested here
        OIIO_CHECK_EQUAL (extract<10>(b), 10);
                          ^
src/libutil/simd_test.cpp:1702:5: note: in instantiation of function template specialization 'test_component_access<OpenImageIO_v1_9::simd::vfloat4>' requested here
    test_component_access<vfloat4> ();
    ^
In file included from src/libutil/simd_test.cpp:37:
src/include/OpenImageIO/simd.h:3229:29: error: argument value 767 is outside the valid range [0, 255] [-Wargument-outside-range]
    return _mm_castsi128_ps(_mm_shuffle_epi32(_mm_castps_si128(a), _MM_SHUFFLE(i3, i2, i1, i0)));
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/clang/7.0.0/include/emmintrin.h:4347:12: note: expanded from macro '_mm_shuffle_epi32'
  (__m128i)__builtin_ia32_pshufd((__v4si)(__m128i)(a), (int)(imm))
           ^                                           ~~~~~~~~~~
src/include/OpenImageIO/simd.h:6843:26: note: in instantiation of function template specialization 'OpenImageIO_v1_9::simd::shuffle_sse<11, 11, 11, 11>' requested here
    return _mm_cvtss_f32(shuffle_sse<i,i,i,i>(a.simd()));
                         ^
src/libutil/simd_test.cpp:636:27: note: in instantiation of function template specialization 'OpenImageIO_v1_9::simd::extract<11>' requested here
        OIIO_CHECK_EQUAL (extract<11>(b), 11);
                          ^
src/libutil/simd_test.cpp:1702:5: note: in instantiation of function template specialization 'test_component_access<OpenImageIO_v1_9::simd::vfloat4>' requested here
    test_component_access<vfloat4> ();
    ^
In file included from src/libutil/simd_test.cpp:37:
src/include/OpenImageIO/simd.h:3229:29: error: argument value 1020 is outside the valid range [0, 255] [-Wargument-outside-range]
    return _mm_castsi128_ps(_mm_shuffle_epi32(_mm_castps_si128(a), _MM_SHUFFLE(i3, i2, i1, i0)));
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/clang/7.0.0/include/emmintrin.h:4347:12: note: expanded from macro '_mm_shuffle_epi32'
  (__m128i)__builtin_ia32_pshufd((__v4si)(__m128i)(a), (int)(imm))
           ^                                           ~~~~~~~~~~
src/include/OpenImageIO/simd.h:6843:26: note: in instantiation of function template specialization 'OpenImageIO_v1_9::simd::shuffle_sse<12, 12, 12, 12>' requested here
    return _mm_cvtss_f32(shuffle_sse<i,i,i,i>(a.simd()));
                         ^
src/libutil/simd_test.cpp:637:27: note: in instantiation of function template specialization 'OpenImageIO_v1_9::simd::extract<12>' requested here
        OIIO_CHECK_EQUAL (extract<12>(b), 12);
                          ^
src/libutil/simd_test.cpp:1702:5: note: in instantiation of function template specialization 'test_component_access<OpenImageIO_v1_9::simd::vfloat4>' requested here
    test_component_access<vfloat4> ();
    ^
In file included from src/libutil/simd_test.cpp:37:
src/include/OpenImageIO/simd.h:3229:29: error: argument value 1021 is outside the valid range [0, 255] [-Wargument-outside-range]
    return _mm_castsi128_ps(_mm_shuffle_epi32(_mm_castps_si128(a), _MM_SHUFFLE(i3, i2, i1, i0)));
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/clang/7.0.0/include/emmintrin.h:4347:12: note: expanded from macro '_mm_shuffle_epi32'
  (__m128i)__builtin_ia32_pshufd((__v4si)(__m128i)(a), (int)(imm))
           ^                                           ~~~~~~~~~~
src/include/OpenImageIO/simd.h:6843:26: note: in instantiation of function template specialization 'OpenImageIO_v1_9::simd::shuffle_sse<13, 13, 13, 13>' requested here
    return _mm_cvtss_f32(shuffle_sse<i,i,i,i>(a.simd()));
                         ^
src/libutil/simd_test.cpp:638:27: note: in instantiation of function template specialization 'OpenImageIO_v1_9::simd::extract<13>' requested here
        OIIO_CHECK_EQUAL (extract<13>(b), 13);
                          ^
src/libutil/simd_test.cpp:1702:5: note: in instantiation of function template specialization 'test_component_access<OpenImageIO_v1_9::simd::vfloat4>' requested here
    test_component_access<vfloat4> ();
    ^
In file included from src/libutil/simd_test.cpp:37:
src/include/OpenImageIO/simd.h:3229:29: error: argument value 1022 is outside the valid range [0, 255] [-Wargument-outside-range]
    return _mm_castsi128_ps(_mm_shuffle_epi32(_mm_castps_si128(a), _MM_SHUFFLE(i3, i2, i1, i0)));
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/clang/7.0.0/include/emmintrin.h:4347:12: note: expanded from macro '_mm_shuffle_epi32'
  (__m128i)__builtin_ia32_pshufd((__v4si)(__m128i)(a), (int)(imm))
           ^                                           ~~~~~~~~~~
src/include/OpenImageIO/simd.h:6843:26: note: in instantiation of function template specialization 'OpenImageIO_v1_9::simd::shuffle_sse<14, 14, 14, 14>' requested here
    return _mm_cvtss_f32(shuffle_sse<i,i,i,i>(a.simd()));
                         ^
src/libutil/simd_test.cpp:639:27: note: in instantiation of function template specialization 'OpenImageIO_v1_9::simd::extract<14>' requested here
        OIIO_CHECK_EQUAL (extract<14>(b), 14);
                          ^
src/libutil/simd_test.cpp:1702:5: note: in instantiation of function template specialization 'test_component_access<OpenImageIO_v1_9::simd::vfloat4>' requested here
    test_component_access<vfloat4> ();
    ^
In file included from src/libutil/simd_test.cpp:37:
src/include/OpenImageIO/simd.h:3229:29: error: argument value 1023 is outside the valid range [0, 255] [-Wargument-outside-range]
    return _mm_castsi128_ps(_mm_shuffle_epi32(_mm_castps_si128(a), _MM_SHUFFLE(i3, i2, i1, i0)));
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/clang/7.0.0/include/emmintrin.h:4347:12: note: expanded from macro '_mm_shuffle_epi32'
  (__m128i)__builtin_ia32_pshufd((__v4si)(__m128i)(a), (int)(imm))
           ^                                           ~~~~~~~~~~
src/include/OpenImageIO/simd.h:6843:26: note: in instantiation of function template specialization 'OpenImageIO_v1_9::simd::shuffle_sse<15, 15, 15, 15>' requested here
    return _mm_cvtss_f32(shuffle_sse<i,i,i,i>(a.simd()));
                         ^
src/libutil/simd_test.cpp:640:27: note: in instantiation of function template specialization 'OpenImageIO_v1_9::simd::extract<15>' requested here
        OIIO_CHECK_EQUAL (extract<15>(b), 15);
                          ^
src/libutil/simd_test.cpp:1702:5: note: in instantiation of function template specialization 'test_component_access<OpenImageIO_v1_9::simd::vfloat4>' requested here
    test_component_access<vfloat4> ();
    ^
12 errors generated.
```

Full build log: https://ptpb.pw/TmYe (oiio-1.7.17)

### Steps to Reproduce

1. Install Clang 7.0
2. Set `CC`/`CXX`/`CPP`/`CXXCPP` to Clang 7.0
3. `cmake /path/to/oiio`
4. `make`

or (FreeBSD -CURRENT kernel)

1. `poudriere jail -cj clang7 -a amd64 -v projects/clang700-import -m svn+https`
2. `poudriere testport -j clang7 graphics/py-openimageio`

### Versions

* OIIO branch/version: master aka 17ab627d6dd111ce65d8165ba12bceebca3466d2
* OS: FreeBSD 12.0@[r337285](https://svnweb.freebsd.org/changeset/base/337285) + /projects/clang700-import@[r337355](https://svnweb.freebsd.org/changeset/base/337355)
* C++ compiler: Clang 7.0@[r338892](https://reviews.llvm.org/rL338892)

**Comment by lgritz** [comment]
Proposed fixes in #1995

**Comment by lgritz** [comment]
Fixed in #1995
