### ISSUE TITLE
boost 1.60 fails building with `no matching function for call to 'registry_lookup2'`

### ISSUE THREAD

**Issue by svenstaro** [OpenImageIO/oiio#1299]
Arch Linux, gcc 5.3, boost 1.60. Compiles fine when disabling Python.

Build log: http://b.1339.cf/apfwyxv.log

**Comment by lgritz** [comment]
I looked at the log, and it's not an error I've seen before. Something is confusing Boost.Python.

Which OS and flavor is this?

Does it work on that platform for Boost 1.59?

Does it work with Boost 1.60 if you compile for C++11?

**Comment by svenstaro** [comment]
Yes, works with 1.59. No, does not work for C++11. It's specifically a boost.python issue with 1.60. For OS and stuff, see above.

**Comment by lgritz** [comment]
I'll try downloading Boost 1.60 (which was just released a couple days ago) and see if I can reproduce on my end.

**Comment by lgritz** [comment]
The weird thing is that the Boost 1.60 release notes don't mention anything has changed with Boost.Python.

**Comment by lgritz** [comment]
The good (?) news is that I am able to reproduce this with boost 1.60 on my machine. So hang on, will work on this tomorrow.

**Comment by lgritz** [comment]
Fix proposed in #1300.

**Comment by david-geiger** [comment]
Hi,

I confirm that with the proposed fix openimageio-1.6.8 built fine now against boost 1.60.0 on Mageia Cauldron.

So, is it possible to fix 1.5 branch too?

Regards,
David

**Comment by lgritz** [comment]
I can't backport this to 1.5, it's too big a change (and compatibility break) for a stable release (let alone an obsolete one), but I can just disable the particular Python binding calls for ImageCache that don't compile correctly (they wouldn't have worked right anyway, so I think we can live with disabling them).

I'll push these fixes to master, RB-1.6, and RB-1.5 today.
