### ISSUE TITLE
Lose Matadata on iff Format

### ISSUE THREAD

**Issue by ArashHosseini** [OpenImageIO/oiio#1546]
### Problem

Hey, i lose the meta data on iff format, i use the same method for **exr** and it **works fine** but on iff i get only the compression back, the added metadata is a dict with random strings as key and value (i check the architecture valid system size of the inputs before )

**Expected behavior:** [I would except to added input back]

**Actual behavior:** [get only the compression back]
### Versions
- OIIO branch/version: 1.5
- OS: centos-6,_x86-64
- C++ compiler:

**Comment by lgritz** [comment]
This isn't exactly a detailed recipe to reproduce the problem.

How are you writing the iff file? What metadata do you believe should be there, which is missing? How are you determining that it's not in the file?

**Comment by lgritz** [comment]
Also, can you reproduce the problem on a currently-supported branch, 1.7 or master?

**Comment by ArashHosseini** [comment]
i have not the possibility to test it under 1.7 version 

the current result of is get_image_data(befor adding new data, 'source file'): 
```
 { "Artist":"XY , Architecture",
   "DateTime":"TIME XY", 
   "compression":"rle" }
```
the current result of is get_image_data(after adding new data):  
`{"compression":"rle"}   `

my exception would be: 

```
 { "Artist":"XY , Architecture",
   "DateTime":"TIME XY", 
   "compression":"rle",
   "test_attr" = "A00000"}

```
**code**:
```
def _get_open_image_input(image_file_path):
      imageinput  = oiio.ImageInput.create(image_file_path)
      if imageinput is not None:
         image = image_input.open(image_file_path)
         if image.geterror():
            return image

#get data
def get_image_data(img_file):
      info_dict = {}
      image_input = _get_open_image_input(img_file)
      if image_input:
         spec = image_input.spec()
         metadict = {}
         for p in spec.extra_attribs:
              metadict[p.name] = spec.metadata_val(p, True).replace('"', '')
              info_dict["meta"] = meta_dict
              return info_dict


# add data
def add_metadata(image, metadata ={}):
       ifile =image
       ofile=ifile.dirname() / ("meta_" + ifile.basename())
       ibuf =oiio.ImageBuf(str(ifile))

       for k in metadata:
            ibuf.specmod().attribute(k, metadata[k])
       ibuf.write(str(ofile))

       if ofile.exists():
          ifile.remove()
          ofile.rename(ifile)
          return True

def test_set_data(*args):
      test_file = "yourpath/iff_checker.iff"
      data_dict = {}
      data_dict["test_attr"] = "A00000"
      # add data
      add_metadata(test_file, data_dict)
      #get data
      get_image_data(test_file)
```

**Comment by lgritz** [comment]
I see now! The iff writer is failing to set the artist and datetime data. That should be an easy fix, I think. I'll give it a try and post a review.

**Comment by lgritz** [comment]
Proposed fix is in PR #1549.

Once it's approved, I will certainly backport to 1.7, and can backport to 1.6 if somebody specifically needs it. But we haven't made a 1.5 release, even for bug fixes, in a many many months. I guess I can do it if it's an emergency for you (assuming it can merge without conflicts), but I'd really like to encourage you to upgrade your OIIO to something recent, ideally 1.7.

**Comment by remusvrm** [comment]
Hi @lgritz
could you please include this fix in 1.6 release as well? We are running on CentOS 6 and 1.7 release doesn't get compiled for us as is configured with option "-std=c++11".
Thanks!

**Comment by lgritz** [comment]
It is possible to build 1.7 without C++11. (The default is C++11, but you can turn it off in 1.7, you cannot do so in 1.8.)

If you use the top-level make wrapper, you can just "make USE_CPP11=0".

If you use CMake directly, you want 'mkdir build/linux ; cd build/linux ; cmake -DUSE_CPP11=0 ../..'

I can still try to backport to 1.6 if you want, but if this is all it takes for you to switch to 1.7, then that is a better choice because you'll get so many more fixes and enhancements in the process.

**Comment by remusvrm** [comment]
Hi @lgritz , thanks for your advice! Unfortunately, oiio doesn't get compiled on CentOS 6.7 because of gcc 4.4.7. I checked this issue #1292. Is there any workaround?

Error message:
```
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/x86_64-redhat-linux/bits/c++allocator.h:34,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/allocator.h:48,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/string:43,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/locale_classes.h:42,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/ios_base.h:43,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ios:43,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/istream:40,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/fstream:40,
                 from .../openimageIO/1.7.8/src/oiio-Release-1.7.8/src/openexr.imageio/exrinput.cpp:35:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ext/new_allocator.h: In instantiation of ‘__gnu_cxx::new_allocator<const std::basic_string<char, std::char_traits<char>, std::allocator<char> > >’:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/allocator.h:87:   instantiated from ‘std::allocator<const std::basic_string<char, std::char_traits<char>, std::allocator<char> > >’
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_vector.h:71:   instantiated from ‘std::_Vector_base<const std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<const std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >’
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_vector.h:171:   instantiated from ‘std::vector<const std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<const std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >’
.../openimageIO/1.7.8/src/oiio-Release-1.7.8/src/openexr.imageio/exrinput.cpp:1201:   instantiated from here
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ext/new_allocator.h:79: error: ‘const _Tp* __gnu_cxx::new_allocator<_Tp>::address(const _Tp&) const [with _Tp = const std::basic_string<char, std::char_traits<char>, std::allocator<char> >]’ cannot be overloaded
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ext/new_allocator.h:76: error: with ‘_Tp* __gnu_cxx::new_allocator<_Tp>::address(_Tp&) const [with _Tp = const std::basic_string<char, std::char_traits<char>, std::allocator<char> >]’
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ext/new_allocator.h: In instantiation of ‘__gnu_cxx::new_allocator<const OpenImageIO::v1_7::TypeDesc>’:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/allocator.h:87:   instantiated from ‘std::allocator<const OpenImageIO::v1_7::TypeDesc>’
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_vector.h:71:   instantiated from ‘std::_Vector_base<const OpenImageIO::v1_7::TypeDesc, std::allocator<const OpenImageIO::v1_7::TypeDesc> >’
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_vector.h:171:   instantiated from ‘std::vector<const OpenImageIO::v1_7::TypeDesc, std::allocator<const OpenImageIO::v1_7::TypeDesc> >’
.../openimageIO/1.7.8/src/oiio-Release-1.7.8/src/openexr.imageio/exrinput.cpp:1201:   instantiated from here
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ext/new_allocator.h:79: error: ‘const _Tp* __gnu_cxx::new_allocator<_Tp>::address(const _Tp&) const [with _Tp = const OpenImageIO::v1_7::TypeDesc]’ cannot be overloaded
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ext/new_allocator.h:76: error: with ‘_Tp* __gnu_cxx::new_allocator<_Tp>::address(_Tp&) const [with _Tp = const OpenImageIO::v1_7::TypeDesc]’
.../openimageIO/1.7.8/src/oiio-Release-1.7.8/src/openexr.imageio/exrinput.cpp: In member function ‘virtual bool OpenImageIO::v1_7::OpenEXRInput::read_native_deep_scanlines(int, int, int, int, int, OpenImageIO::v1_7::DeepData&)’:
.../openimageIO/1.7.8/src/oiio-Release-1.7.8/src/openexr.imageio/exrinput.cpp:1201: error:   initializing argument 3 of ‘void OpenImageIO::v1_7::DeepData::init(int, int, OpenImageIO::v1_7::array_view<const OpenImageIO::v1_7::TypeDesc, 1ul>, OpenImageIO::v1_7::array_view<const std::basic_string<char, std::char_traits<char>, std::allocator<char> >, 1ul>)’
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/x86_64-redhat-linux/bits/c++allocator.h:34,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/allocator.h:48,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/string:43,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/locale_classes.h:42,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/ios_base.h:43,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ios:43,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/istream:40,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/fstream:40,
                 from .../openimageIO/1.7.8/src/oiio-Release-1.7.8/src/openexr.imageio/exrinput.cpp:35:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ext/new_allocator.h: At global scope:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ext/new_allocator.h: In instantiation of ‘__gnu_cxx::new_allocator<const unsigned int>’:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/allocator.h:87:   instantiated from ‘std::allocator<const unsigned int>’
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_vector.h:71:   instantiated from ‘std::_Vector_base<const unsigned int, std::allocator<const unsigned int> >’
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_vector.h:171:   instantiated from ‘std::vector<const unsigned int, std::allocator<const unsigned int> >’
.../openimageIO/1.7.8/src/oiio-Release-1.7.8/src/openexr.imageio/exrinput.cpp:1228:   instantiated from here
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ext/new_allocator.h:79: error: ‘const _Tp* __gnu_cxx::new_allocator<_Tp>::address(const _Tp&) const [with _Tp = const unsigned int]’ cannot be overloaded
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ext/new_allocator.h:76: error: with ‘_Tp* __gnu_cxx::new_allocator<_Tp>::address(_Tp&) const [with _Tp = const unsigned int]’
make[2]: *** [src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/openexr.imageio/exrinput.cpp.o] Error 1
make[2]: Leaving directory `.../openimageIO/1.7.8/src/oiio-Release-1.7.8/build'
make[1]: *** [src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/all] Error 2
make[1]: Leaving directory `.../openimageIO/1.7.8/src/oiio-Release-1.7.8/build'
make: *** [all] Error 2
[  0%] Built target CopyFiles
[  7%] Built target OpenImageIO_Util
[  8%] Built target array_view_test
[  9%] Built target atomic_test
[ 10%] Built target filesystem_test
[ 10%] Building CXX object src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/openexr.imageio/exrinput.cpp.o
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/x86_64-redhat-linux/bits/c++allocator.h:34,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/allocator.h:48,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/string:43,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/locale_classes.h:42,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/ios_base.h:43,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ios:43,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/istream:40,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/fstream:40,
                 from .../openimageIO/1.7.8/src/oiio-Release-1.7.8/src/openexr.imageio/exrinput.cpp:35:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ext/new_allocator.h: In instantiation of ‘__gnu_cxx::new_allocator<const std::basic_string<char, std::char_traits<char>, std::allocator<char> > >’:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/allocator.h:87:   instantiated from ‘std::allocator<const std::basic_string<char, std::char_traits<char>, std::allocator<char> > >’
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_vector.h:71:   instantiated from ‘std::_Vector_base<const std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<const std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >’
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_vector.h:171:   instantiated from ‘std::vector<const std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<const std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >’
.../openimageIO/1.7.8/src/oiio-Release-1.7.8/src/openexr.imageio/exrinput.cpp:1201:   instantiated from here
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ext/new_allocator.h:79: error: ‘const _Tp* __gnu_cxx::new_allocator<_Tp>::address(const _Tp&) const [with _Tp = const std::basic_string<char, std::char_traits<char>, std::allocator<char> >]’ cannot be overloaded
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ext/new_allocator.h:76: error: with ‘_Tp* __gnu_cxx::new_allocator<_Tp>::address(_Tp&) const [with _Tp = const std::basic_string<char, std::char_traits<char>, std::allocator<char> >]’
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ext/new_allocator.h: In instantiation of ‘__gnu_cxx::new_allocator<const OpenImageIO::v1_7::TypeDesc>’:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/allocator.h:87:   instantiated from ‘std::allocator<const OpenImageIO::v1_7::TypeDesc>’
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_vector.h:71:   instantiated from ‘std::_Vector_base<const OpenImageIO::v1_7::TypeDesc, std::allocator<const OpenImageIO::v1_7::TypeDesc> >’
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_vector.h:171:   instantiated from ‘std::vector<const OpenImageIO::v1_7::TypeDesc, std::allocator<const OpenImageIO::v1_7::TypeDesc> >’
.../openimageIO/1.7.8/src/oiio-Release-1.7.8/src/openexr.imageio/exrinput.cpp:1201:   instantiated from here
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ext/new_allocator.h:79: error: ‘const _Tp* __gnu_cxx::new_allocator<_Tp>::address(const _Tp&) const [with _Tp = const OpenImageIO::v1_7::TypeDesc]’ cannot be overloaded
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ext/new_allocator.h:76: error: with ‘_Tp* __gnu_cxx::new_allocator<_Tp>::address(_Tp&) const [with _Tp = const OpenImageIO::v1_7::TypeDesc]’
.../openimageIO/1.7.8/src/oiio-Release-1.7.8/src/openexr.imageio/exrinput.cpp: In member function ‘virtual bool OpenImageIO::v1_7::OpenEXRInput::read_native_deep_scanlines(int, int, int, int, int, OpenImageIO::v1_7::DeepData&)’:
.../openimageIO/1.7.8/src/oiio-Release-1.7.8/src/openexr.imageio/exrinput.cpp:1201: error:   initializing argument 3 of ‘void OpenImageIO::v1_7::DeepData::init(int, int, OpenImageIO::v1_7::array_view<const OpenImageIO::v1_7::TypeDesc, 1ul>, OpenImageIO::v1_7::array_view<const std::basic_string<char, std::char_traits<char>, std::allocator<char> >, 1ul>)’
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/x86_64-redhat-linux/bits/c++allocator.h:34,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/allocator.h:48,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/string:43,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/locale_classes.h:42,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/ios_base.h:43,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ios:43,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/istream:40,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/fstream:40,
                 from .../openimageIO/1.7.8/src/oiio-Release-1.7.8/src/openexr.imageio/exrinput.cpp:35:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ext/new_allocator.h: At global scope:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ext/new_allocator.h: In instantiation of ‘__gnu_cxx::new_allocator<const unsigned int>’:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/allocator.h:87:   instantiated from ‘std::allocator<const unsigned int>’
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_vector.h:71:   instantiated from ‘std::_Vector_base<const unsigned int, std::allocator<const unsigned int> >’
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_vector.h:171:   instantiated from ‘std::vector<const unsigned int, std::allocator<const unsigned int> >’
.../openimageIO/1.7.8/src/oiio-Release-1.7.8/src/openexr.imageio/exrinput.cpp:1228:   instantiated from here
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ext/new_allocator.h:79: error: ‘const _Tp* __gnu_cxx::new_allocator<_Tp>::address(const _Tp&) const [with _Tp = const unsigned int]’ cannot be overloaded
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ext/new_allocator.h:76: error: with ‘_Tp* __gnu_cxx::new_allocator<_Tp>::address(_Tp&) const [with _Tp = const unsigned int]’
make[2]: *** [src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/__/openexr.imageio/exrinput.cpp.o] Error 1
make[1]: *** [src/libOpenImageIO/CMakeFiles/OpenImageIO.dir/all] Error 2
make: *** [all] Error 2

```

**Comment by lgritz** [comment]
I'm not inclined to fight to make OIIO 1.7 compile with with gcc 4.4.

I'll backport the IFF fix you need to 1.6.

**Comment by lgritz** [comment]
I believe I already did port this back to 1.6. Have you tried building Release-1.6.18?

**Comment by remusvrm** [comment]
> I'm not inclined to fight to make OIIO 1.7 compile with with gcc 4.4.

This is what I was thinking, too.
Thanks for your help!

**Comment by ArashHosseini** [comment]
Hey Larry, my current test environment is the 1.6.18, still losing the meta data on .iff.

**Comment by lgritz** [comment]
Are you using specifically the commit with the "Release-1.6.18" tag? Or some earlier tag that just happens to be after we bumped the version number but before the actual release?

**Comment by lgritz** [comment]
Because Release-1.6.18 absolutely positively contains the patch for IFF described in this ticket. There is nothing left to merge, it's already there.

**Comment by ArashHosseini** [comment]
e31518075bb8283e9526a5201590bcf639d1e296 is the current commit, read/write method still the same like my post from Oct 28.

**Comment by lgritz** [comment]
I wonder if maybe we have different expectations.

The fix that I've added addressed the problem of the "DateTime" and "Artist" metadata being accidentally left out when writing IFF files. I'm quite certain that this is fixed now in master (1.8), 1.7, and 1.6.

However, these are the few fields that are supported with IFF. To the best of my knowledge, the IFF format does not support "arbitrary metadata" in the way that, say, OpenEXR does. If that's what you are expecting, I think IFF is really the wrong format to be using.

**Comment by ArashHosseini** [comment]
Hey Larry, 
ok i get it.
